name: News Push

on: [push]

jobs:
  builder:
    name: Builder
    runs-on: [ubuntu-latest]
    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set Permissions
      run: chmod -x /gradlew
      
    - name: clean and check
      env:
        GRADLE_USER_HOME: "/gradle"
      run: ./gradlew -Penvironment=DEV
                  clean
                  check
                  --warning-mode all
                  -s
