name: News Push

on: [push]

jobs:
  build:
    name: Builder
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Set Permissions
      run: sudo chmod -x gradlew
      
    - name: Clean
      run: sudo ./gradlew clean
    - name: Check
      run: sudo ./gradlew check
             
